services:
  backend:
    build: ./backend
    ports:
      - "5000:80"  # Exposing backend on port 5000 of host
    environment:
      - FLASK_ENV=production
    networks:
      - default

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_BASE_URL=https://shimmering-insight-production.up.railway.app  # Use the backend service name
    networks:
      - default

networks:
  default:
    external: true
    name: task_management_default

